### ISSUE TITLE
Document Archive

### ISSUE THREAD

**Issue by bru** [100hours/100hours#4]
Store those documents online as they are completed, creating an archive on the site as I go.

The archive should be easily browsable. Ideas on how to make that efficient (tagging? time based stream?) are welcome

**Comment by bru** [comment]
Search is not part of this feature as yet.

**Comment by alexslade** [comment]
@bru I was imagining this would just be the document list. It will be filterable (not searchable as such, but you can filter by the title).

**Comment by bru** [comment]
Sounds good to me. There is a chance that the document list grows a lot, we may want to put the list in a scrollable div.

**Comment by alexslade** [comment]
Agreed

Sent from my phone

On 12 Dec 2012, at 16:20, Riccardo Cambiassi notifications@github.com
wrote:

Sounds good to me. There is a chance that the document list grows a lot, we
may want to put the list in a scrollable div.

—
Reply to this email directly or view it on
GitHubhttps://github.com/100hours/100hours/issues/4#issuecomment-11295817.
